version: '2.2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - unifi
    ports:
      - "37117:27117"
    restart: always
    volumes:
      - db:/data/db
  controller:
    build: "."
    depends_on:
      - mongo
    init: true
    # networks:
    #   - unifi
    network_mode: host
    restart: always
    volumes:
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
    environment:
      DB_URI: mongodb://localhost:37117/unifi
      STATDB_URI: mongodb://localhost:37117/unifi_stat
      DB_NAME: unifi
      RUNAS_UID0: "false"
      TZ: "Europe/Amsterdam"
    # ports:
    #   - "9090:9090"
    #   - "8443:8443"
    #   - "3478:3478/udp"
    #   - "10001:10001/udp"
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - log:/unifi/log

volumes:
  db:
  data:
  log:
  cert:
  init:

networks:
  unifi:
